#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad-plus-plus for snap
#
# Date: Feb 11 2018
#

dli7z16 () {
    ARCHITECTURE=$(dpkg --print-architecture)
    if [ "${ARCHITECTURE}" = "amd64" ]; then
    debs="https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb"
    debsi="p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb"
    elif [ "${ARCHITECTURE}" = "i386" ]; then
    debs="https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip_16.02+dfsg-4_i386.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip-full_16.02+dfsg-4_i386.deb"
    debsi="p7zip_16.02+dfsg-4_i386.deb p7zip-full_16.02+dfsg-4_i386.deb"
    else
     echo "ERROR! No amd64 or i386 system found. Failing the build here."
     exit 1
    fi

    for dldebs in $debs
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in $debsi
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mknpp () {
  
    mkdir ./{wine-runtime,wine-platform,bin} && mkdir -p usr/share/{pixmaps,applications} 
    find "usr" -type d -execdir chmod 755 {}  
}

# mkdsk () {
# cat > notepad-plus-plus.desktop <<'EOF1'
# [Desktop Entry]
# Name=Notepad++
# GenericName=Text Editor
# Comment=Simple and free source code editor.
# Encoding=UTF-8
# Version=
# Type=Application
# Terminal=false
# Icon=${SNAP}/usr/share/pixmaps/notepad-plus-plus.png
# Exec=notepad-plus-plus %F
# StartupWMClass=notepad-plus-plus.exe
# Categories=Utility;TextEditor
# MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh;application/x-wine-extension-ini;application/x-wine-extension-inf;
# EOF1
# sed -i -e 's|Version=|Version='"$ver"'|g' notepad-plus-plus.desktop
# }

dli7z16
mknpp

cp -R -p {bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL