name: visualg
version: 3.0.7
summary: português estruturado (portugol)
description: |
 O Visualg é um programa que permite criar, editar, interpretar e que também executa os algoritmos em português estruturado (portugol) como se fosse um “programa” normal de computador.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-3-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-3-stable
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  visualg:
    command: visualg
    environment:
      visualg: $SNAP/visualg
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media, icon-themes, wine-runtime, wine-3-stable ]

parts:
  visualg:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
    build-packages: [wget]

  visualg30:
    plugin: dump
    source: snap/local
    source-type: local
    stage:
      - visualg30.exe
      - VISUALG30.INI
      - visualg
      - visualg.png
